# Generated by Django 5.1.1 on 2024-10-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image1',
            new_name='image',
        ),
    ]
