# Generated by Django 5.1.1 on 2024-11-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='razor_pay_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_id',
            new_name='razor_pay_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
