# Generated by Django 5.1.1 on 2024-11-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_rename_razorpay_order_id_order_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_signature',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
