# Generated by Django 5.1.1 on 2024-11-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_cartitem_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_payment_signature',
            new_name='razorpay_signature',
        ),
    ]
