# Generated by Django 5.1.1 on 2024-12-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
