# Generated by Django 5.1.1 on 2024-11-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Bank Transfer', 'Direct Bank Transfer'), ('PayPal', 'PayPal'), ('Credit Card', 'Credit Card (Stripe)')], default='COD', max_length=50),
        ),
    ]
