# Generated by Django 5.1.1 on 2024-11-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
