# Generated by Django 5.1.1 on 2024-11-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_order_amount',
        ),
    ]
