# Generated by Django 5.1.1 on 2024-11-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_order_final_price_order_coupon_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit',
        ),
    ]
