# Generated by Django 5.1.1 on 2024-11-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Bank Transfer', 'Direct Bank Transfer'), ('PayPal', 'PayPal'), ('Razorpay', 'Razorpay')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Bank Transfer', 'Direct Bank Transfer'), ('PayPal', 'PayPal'), ('Razorpay', 'Razorpay')], max_length=50),
        ),
    ]
