# Generated by Django 5.1.1 on 2024-12-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_order_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Bank Transfer', 'Direct Bank Transfer'), ('PayPal', 'PayPal'), ('Razorpay', 'Razorpay'), ('Wallet', 'Wallet')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Bank Transfer', 'Direct Bank Transfer'), ('PayPal', 'PayPal'), ('Razorpay', 'Razorpay'), ('Wallet', 'Wallet')], max_length=50),
        ),
    ]
