# Generated by Django 5.1.1 on 2024-11-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
