# Generated by Django 5.1.1 on 2024-11-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_profile_from_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='from_flag',
        ),
    ]
